### ISSUE TITLE
CC 2017

### ISSUE THREAD

**Issue by gitguys** [ChrisMcKee/gitweaver#13]
Will this work with Dreamweaver CC 2017?

**Comment by ChrisMcKee** [comment]
Hi see https://github.com/ChrisMcKee/gitweaver/issues/11

**Comment by bymagnum** [comment]
Hi 

solved the problem with Dreamweaver CC 2017 ?

**Comment by ChrisMcKee** [comment]
@bymagnum I've no real plans on touching this as per #11 
There's a solution listed.
https://github.com/ChrisMcKee/gitweaver/issues/11#issuecomment-191163962
